### PR TITLE
Dynamically load the hook details

### PR DESCRIPTION
**Pull request by sigv**
The commit message and the code describe this all much better, but essentially:

1. Hooks get stored in a JSON file.
2. Application pulls in that JSON file.
3. Magic rules that are in the JSON file get applied.

All feedback is appreciated. / @pylerSM @th3an7 
By the way, can we have a v2.0.0 release for when we merge this change?

### CODE REVIEW

**Comment by iHelp101** [comment]
I am happy to see this was improved upon. We started this about 6-7 months ago and it never got pushed out (Remote-hook branch). I don't believe the network state permission is needed. The last issue we never went over was GitHub being blocked in certain countries. We would need at least one alternate source to help with this issue.

**Comment by sigv** [comment]
Yeah, I noticed the old branch so I took in the ideas from that and developed on to of that to get this.

Actually, it makes sense if the permission is not required since the code is executed in the context of the YouTube application and that is the one that holds the permissions. I will check real quick and then drop the permission from the manifest.

What mirror do you recon we should use?

**Comment by iHelp101** [comment]
For my module (XInsta) I use GitHub and Pastebin as my primary sources. I very rarely get complaints about hooks not being able to be fetched. However, it may be better to use an option that allow collaboration (Similar to GitHub). Otherwise you are depending on one person to update the source. It could be rolled out with GitHub for the start and see if any issue occur.

**Comment by sigv** [comment]
I want to hear what @th3an7 thinks of this structure because he is the one who is always first to updating the files and I also want to hear what @pylerSM thinks because, well, it is he who owns the project.

**Comment by sigv** [comment]
If there are issues with GitHub being inaccessible from some locations, we can work on mirrors for sure. I do not think that to be so important, but if it actually is, it can be taken care of.

**Comment by th3an7** [comment]
Well... I am not an owner or sth - I am just updating it and pushing only
my commits (those which does not change anything important :P)

I think it is great idea - we wouldn't have to make new apk for every small
change (right?). For example right now, I can't upload already updated
module (it's working, using it right know) because repo is offline (error
502 when trying to login with XDA...)

I would be fine if it really does work - but I guess last word for this is
to @pylerSM as it is his module and he is the owner of this code :)

**Comment by th3an7** [comment]
Also about github sources being blocked - I don't think they are blocked somewhere... maybe some kind of North Korea (sorry??)... But if they really are, as @iHelp101 said - Pastebin could be a mirror. Basically, every page that can save text which is accessible for everyone under same URL could be a mirror (right?).

**Comment by sigv** [comment]
Yeah, as I said, I want you to check this out because you usually update the files for new releases because you are the quickest to do so. 😄 

I have heard GitHub get banned in China, but the Chinese population doesn't have proper access to Google products and therefore YouTube as far as I understand it. We can use any service that allows serving the file as raw plaintext and that allows modifications to files without their URLs changing.

**Comment by sigv** [comment]
Okay, so lets wait for @pylerSM to voice his opinion on this PR and we are good to merge & release then. 👍

**Comment by th3an7** [comment]
Can someone please update the .json file though? I think it lacks some of the latest YT app rules, does it?
Or just leave it as it is and wait for release time to update it then :P

**Comment by sigv** [comment]
Yeah, I pushed the update on the `master` branch as the change didn't really affect anyone so that it is there.

**Comment by th3an7** [comment]
I just thought about this - now we have 2 versions of module - one with notification visible all the time and one with visible only in background... would it be hard to make simple GUI with 2 buttons to choose which version would be used (so the buttons would be connected to 2 different json files)?

**Comment by sigv** [comment]
It shouldn't be that hard, but right now I can't promise putting in any time so I can't really provide any real estimates for that.

**Comment by th3an7** [comment]
No problem, that answer satisfies me :P
Let's just make initial 2.0 version and if everything goes right, then
experimenting with that :D

**Comment by th3an7** [comment]
OK guys... I have very good news for you - I think we are ready for that 2.0 release :D

I've built new apk for tests and everything works well - json file is loaded (from my fork with modified content to make notification work only in backgroud :P), notification is visible and videos are played constantly :D

I will make one more test (modifying json and loading it one more time) to make sure everything will work for future versions :)

**Comment by th3an7** [comment]
Forgot about this - if someone wants to test it himself, here is new apk file - [https://drive.google.com/file/d/0B8j7vCsf6RXcRExqUnh1QlM0aDg/view?usp=drivesdk](url)

**Comment by th3an7** [comment]
Ok guys - quick question... which apk should I upload to the repo - the normal one (so normal update process) or the new one with json file working (no more apk updates)?

**Comment by sigv** [comment]
If we are comfortable releasing this change, then I suppose we can merge this PR and release with this change. No word from @pylerSM.

About updates and killing the app - the file is downloaded each time the YouTube package is loaded. That happens once when the device boots and each time after that when the application is started. If the app is still in the recents list it is usually still in the memory unless the device is low on memory so the easiest way to force an update of the hooks file is to swipe the YouTube app out of the recents list. I set it up this way because this means that we do not reload the hooks while the app is running - only attaching the hooks once - and this also means that if the app is updated, the hooks get reloaded - no need to reboot the device or anything along those lines.

**Comment by th3an7** [comment]
So merge these and we are done :D
BTW: Have you tested that apk I've posed earlier? It's connected to my fork with json file with modified classes (so notification is visible only in background)... Now, if those commits would be merged, I should rebuild apk which would be connected with json in this source (but notification will be visible all the time.

So - rebuild apk and release that way OR leave it as it is for now and release this way?

**Comment by th3an7** [comment]
OR release normal apks and 2.0 version as experimental in xposed repo?

**Comment by sigv** [comment]
Release normal APK and then release this PR as experimental sounds good. I think we should release the experimental with the hooks file from this repository.

**Comment by th3an7** [comment]
Yeah, so I will rebuild apk with modified link :D

**Comment by sigv** [comment]
The PR already links to the `master` branch, just as it should be released. If there are new changes to the hooks file, they should go in the `master` where they go public right away, instead of depending on forks - be it mine or yours or someone else's.

**Comment by th3an7** [comment]
Aaaaand it's done - I hope nobody will be angry on me - I've uploaded 2 versions of 2.0 release - one pointing to this json, and one to that on my fork - if someone wants specific version, they can choose now :D

**Comment by sigv** [comment]
Do they have the same version code? If so, how does the repository deal with that? How does the Xposed app deal with that? _shrugs_
If we don't hear back from @pylerSM until tomorrow, I am merging this. We can then go ahead and release this as stable.

**Comment by th3an7** [comment]
Ooops... never thought about that XD - let me fix that real quick :P

**Comment by sigv** [comment]
Then again, if they are different version codes then the Xposed app will suggest you to upgrade for one of them, because, well, it will be considered outdated.

**Comment by sigv** [comment]
That change really deserves its own PR and we should not have multiple releases this way.. _sighs_

**Comment by th3an7** [comment]
OK, i will remove the one that points to mine fork - I'll just leave it that way for now :P

**Comment by sigv** [comment]
:+1: for that for now at least.

**Comment by sigv** [comment]
@iHelp101 Do you feel okay with deleting the `remote-hooks` branch so that we do not have old branches laying around?

**Comment by iHelp101** [comment]
Feel free to delete the branch. I am glad to see the idea was improved and expanded on.

**Comment by sigv** [comment]
Taken care of. Thank you for starting on the ground work.
Seems to be some people are getting crashes possibly caused by the new version for some reason. Will try sort that out as soon as I get logs from someone.

**Comment by sigv** [comment]
Apparently, it seems to be caused by me using a helper method introduced in Xposed version 82. _sighs_
Will work around that.

**Comment by sigv** [comment]
@th3an7 Can you please do a new 2.x version? I reintroduced support for old versions (<82) of the Xposed framework in 3b225e7 and that should go to experimental as well so that we can make sure everything is working fine now for everyone.

**Comment by th3an7** [comment]
Sure, when I'll get access to my PC, I'll update it and upload apk... which
version should it have? 2.0.01? :P

**Comment by sigv** [comment]
Yeah, 2.0.1 sounds good because it is a small bug fix. Thanks!

**Comment by pylerSM** [comment]
Everything is fine, thanks for patch! :) I am just busy these days :D

**Comment by th3an7** [comment]
Uploaded updated apk to repo as experimental with version 2.0.1

**Comment by nothingface0** [comment]
Works really well! Thank you guys.

**Comment by haoyangw** [comment]
This is awesome! Thanks guys! Appreciate all your hard work :D This truly fixes the issue of YouTube updates

**Pull request merged**
