### PR TITLE
Update for YT 12.07.63

### PR DESCRIPTION
**Pull request by th3an7**
Update for YT 12.07.63 - Not sure about "cip" class - it is visible in code (in class "cil") but it redirects to previous version (12.07.61)

### CODE REVIEW

**Comment by esgie** [comment]
While patching the newest version via Lucky Patcher (still working!!! :P) I saw that the one pattern was moved to classes2.dex.
So probably that is the place where you'll have to look for the remaining parts of code.

**Comment by th3an7** [comment]
Oh, nice :D
But will json file be different or the same (with updated classes ofc)... I
mean do I need to put something else beside new classes?

**Comment by th3an7** [comment]
Can comfirm that this "cip" class has been moved to classes2.dex :P

**Comment by sigv** [comment]
JSON should be the same. If it works, go for a merge or just cherry-pick it and push it directly. :+1:

**Pull request merged**
