### PR TITLE
Bump for 11.20.54

### PR DESCRIPTION
**Pull request by sigv**
This PR aims to adds support for 11.20.54. Nothing else changed.

### CODE REVIEW

**Comment by sigv** [comment]
cc: @pylerSM @th3an7

**Comment by th3an7** [comment]
Works, module updated...

I can see there was a change to notification. It no longer shows itself when YT app is opened and video is played. It is shown only when in background or screen is locked.

**Comment by sigv** [comment]
True. I like that change, but some might think it is due to the module.. so maybe you can add some message to the update details/changelog saying that the YouTube application (from v11.20.54)

**Comment by th3an7** [comment]
changelog updated

**Comment by Phoenix09** [comment]
METHOD_1 should be `e` not `f`
that's the reason it's not showing the notification when foreground

**Comment by Phoenix09** [comment]
also https://github.com/Phoenix09/YouTubeBackgroundPlayback/commit/d6acc419b72b0f9aa3f15ada25e5ab282dc86143

**Comment by sigv** [comment]
I haven't been decompiling the code into Java, but this seemed like a sane choice for me.. Will have a second look into this, I suppose.

**Comment by sigv** [comment]
@Phoenix09 You are right. That's my bad. However, I think I will keep using the mistake I made in my personal builds as I like that behaviour much better. To each his own, I suppose.

@th3an7 Sorry. You might want to do an update in the repo for this.

**Comment by Bec-de-Xorbin** [comment]
Why not make that "mistake" behaviour default? It makes no sense to have the notification when Youtube is foreground.

**Comment by th3an7** [comment]
There are some people that says Youtube is closing itself when notification is not persistent

**Comment by sigv** [comment]
That's probably due to low memory being available to the device.. but that should not happen to applications running in foreground.

@th3an7 Would it be possible for you to get a log (logcat) from someone about this?

**Comment by th3an7** [comment]
@sigv I saw people complaining here so... it didn't happen to me. They are using apps like Greenify, that's is why it sometimes closes for them. We could make 2 separate verisons - one with notification visible and one with not. The second one could be set as new module or made as beta. Thanks to it, people could just install the version with or without notification.

**Comment by sigv** [comment]
@th3an7 Maybe make it as an option for the same module instead?

**Pull request merged**
