### PR TITLE
YtMusic 3.19.54

### PR DESCRIPTION
**Pull request by SammyTRK**

### CODE REVIEW

**Comment by SammyTRK** [comment]
I hope I got the brackets right. lol.

**Comment by th3an7** [comment]
Seems good :P
Merging it then - good work :)

**Comment by SammyTRK** [comment]
Thanks. Until they make some big changes to the app I think I can keep the hooks updated.

**Comment by th3an7** [comment]
Sure - just push the hooks alone and if they are working I'll be merging them :D

**Pull request merged**
