### PR TITLE
Fix for 12.36.55

### PR DESCRIPTION
**Pull request by th3an7**
Some shit has changed - missing 3rd class...

### CODE REVIEW

**Comment by dakotagrvtt** [comment]
Sounds like they've caught on

**Comment by th3an7** [comment]
Yeah... after 3 years... congrats Google...

**Comment by esgie** [comment]
Updated Lucky Patcher patch to support 12.36.55
http://www59.zippyshare.com/v/YNTnnh7u/file.html[/DLINK]
https://mega.nz/#!Xp5Ega4a!vVau4nRe3xMpJVGhHxU7okMwO4tKc-gZiqKrL2nVn1M

Making this fix took me about 30min so guess the changes made by Google aren't that bad.
If I may be any of help, in my patch (which is based on some old version of this xposed module) the pattern which shall be considered as an equivalent of the 3rd hook from your code has been rewritten to force method:
zan;->d(Lacwa;)Z
to always return true.

**Comment by abhijeetramgir** [comment]
I pasted the file in Android/*. LACK/files/LuckyPatcher
But it still doesn't work.
Can you please tell me how patch this file?
Thanks

**Comment by abhijeetramgir** [comment]
Nevermind, I just opened the file  and lucky patcher imported it.
Thanks for your work!

**Pull request merged**
