### PR TITLE
14.22.54

### PR DESCRIPTION
**Pull request by HpNoTiQ56**

### CODE REVIEW

**Comment by HpNoTiQ56** [comment]
My hook is not working though.

**Comment by th3an7** [comment]
They are not working because you need to edit the link to your hooks in this line:

https://github.com/pylerSM/YouTubeBackgroundPlayback/blob/e3c53feb2657837a99a92d2763f0fba5e80a762b/java/com/pyler/youtubebackgroundplayback/YouTubeBackgroundPlayback.java#L47

It should be direct link (click on RAW and then copy link) to your branch... then you just need to compile module with your own sources in Android Studio and you're good to go,

If you'd use your own hooks, you have to edit them separately from the original branch as the link will always point to your own hooks file.

**Comment by th3an7** [comment]
These should work... I'll merge this - check if these will work in about 20 minutes or so (cause sometimes GitHub is laggy af)

**Comment by DanGLES3** [comment]
Confirmed working on 14.22.54

**Pull request merged**
