### PR TITLE
Bump for 11.18.52

### PR DESCRIPTION
**Pull request by sigv**
This PR aims to adds support for 11.18.52. Nothing else changed.

### CODE REVIEW

**Comment by pylerSM** [comment]
Can you post APK also? Would you like to becoma new maintainer of YTBP APK in Xposed repo?

**Comment by th3an7** [comment]
https://drive.google.com/file/d/0B8j7vCsf6RXcQnNPRmhTaUxuRDQ/view?usp=sharing

Here is the apk file. Check if it's working on other devices (it works for me). Also as I said before, I don't know how to change app version in android studio yet so it's just for testing :P

**Comment by iHelp101** [comment]
@th3an7 Open the build.gradle file in the app folder. Change the version name to the desired version.

**Comment by th3an7** [comment]
Thanks @iHelp101 :D

Here is the APK with correct version (bumped to 1.8.17)
https://drive.google.com/file/d/0B8j7vCsf6RXcUWxZd241amoybnM/view?usp=sharing

**Comment by sigv** [comment]
Right now I'm basically just looking for the same signature as in the previous apps, nothing too fancy - but it seems to get the job done. So, yeah, it would probably be viable for me to maintain the application .

Meanwhile, what is up with the `revert-158-bump-111852` branch?

**Comment by pylerSM** [comment]
That branch has been deleted

**Comment by andreacos92** [comment]
I confirm that the new APK (v 1.8.17) works well with YT 11.18.52.
Thank you veri much :)

**Pull request merged**
