### PR TITLE
Yt music

### PR DESCRIPTION
**Pull request by SammyTRK**

### CODE REVIEW

**Comment by th3an7** [comment]
Is everything working? I could give you collaborator to my fork so you can automatically commit changes to YTMusic :P

**Comment by th3an7** [comment]
We'll do it like this - I'll close this without merging anything so you could commit only hooks. Is that OK?

**Comment by SammyTRK** [comment]
Right. This is how I've been using for about a year now. Just decided to push my changes to github. I am trying to figure out how to only give a pull request just for the hook-music.json. Yes its working, I tested it.

**Comment by SammyTRK** [comment]
OK

**Comment by th3an7** [comment]
Edit the file hooks here and try copying yours without any other edits

**Pull request closed without merging**
